function init(self)
	msg.post(".", "acquire_input_focus")
	--msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		print("Touch!")

		local pos = go.get_position()
		pos.x = pos.x + 100 -- <3>
		local carrot_id = factory.create("#carrotfactory", pos) -- <4>
		go.animate(carrot_id, "position.x", go.PLAYBACK_ONCE_FORWARD, 720, go.EASING_LINEAR, 3) -- <5>
	end
end