function init(self)
	particles = {}
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	local particles_id = factory.create("#particle_factory", lastTouchPos)	
	particlefx.play(particles_id)
	
	local function deleteParticles()
		go.delete(particles_id)
	end
	t = timer.delay(0.3, false, deleteParticles)
end

